import "@mantine/core/styles.css";
import "../styles/globals.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { MantineProvider, createTheme, ColorSchemeScript } from "@mantine/core";

import { theme } from "./theme";
import AuthProvider from "../components/providers/AuthProvider";
import { cn } from "../lib/utils";

const font = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
        <link rel="shortcut icon" href="/favicon.svg" />
        <meta
          name="viewport"
          content="minimum-scale=1, initial-scale=1, width=device-width, user-scalable=no"
        />
      </head>

      <body className={cn(font.className, "bg-white dark:bg-[#313338]")}>
        <AuthProvider>
          <MantineProvider theme={theme} defaultColorScheme="dark">
            {children}
          </MantineProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
